trigger:
- master

pool:
  name: Self-Hosted-Agent

variables:
 one: initialValue 
 staticVar: 'my value' # static variable
 compileVar: ${{ variables.staticVar }} # compile time expression
 isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')] # runtime expression

stages:
- stage:
  displayName: "Stage A"
  jobs:
  - job: A1
    steps:
      - script: |
          echo "Tempalte Expression value:" ${{ variables.one }} # outputs initialValue
          echo "Macro variable value:" $(one)
        displayName: First variable pass
      - bash: echo '##vso[task.setvariable variable=one]secondValue'
        displayName: Set new variable value
      - script: |
          echo "Template Expression value:" ${{ variables.one }} # outputs initialValue
          echo "Macro variable value:" $(one) # outputs secondValue
          echo "Macro variable (isMain) value:" $(isMain)
        displayName: Second variable pass
      - bash: echo "Macro variable value:" $(one)
      - powershell: echo "Macro variable value:" $(one)
      - script: echo "Macro variable value:" $(one)
- stage: 
  displayName: "Stage B"
  condition: and(succeeded(), eq(variables.isMain, 'true'))
  jobs:
  - job: B1
    steps:
      - script: echo Hello Stage B!

